# Generated by Django 5.1.2 on 2024-10-22 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etiqueta',
            old_name='etiqueta',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='fecha_creación',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='ttulo',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='usuario_asignado',
            new_name='usuarios_asignados',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_creador', to='ejercicio.usuario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_tarea', to='ejercicio.tarea'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='tarea',
            field=models.ManyToManyField(related_name='etiquetas_tareas', to='ejercicio.tarea'),
        ),
    ]
